mqtt:
  url: tcp://127.0.0.1:1883
  username: ${MQTT_USERNAME:admin}
  password: ${MQTT_PASSWORD:Hyd@qwe}

spring.boot.admin.client:
  enabled: false

xxl.job:
  enabled: false

---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:${DB_PORT:3306}/zm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
          username: ${DB_USERNAME:zm_root}
          password: ${DB_PASSWORD:Huiyeda98315}
        slave:
          lazy: true
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:${DB_PORT:3306}/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
          username: ${DB_USERNAME:zm_root}
          password: ${DB_PASSWORD:Huiyeda98315}
      hikari:
        maxPoolSize: 35
        minIdle: 5
        connectionTimeout: 3000
        validationTimeout: 3000
        idleTimeout: 600000
        maxLifetime: 1800000
        connectionTestQuery: SELECT 1
        keepaliveTime: 300000
        leakDetectionThreshold: 60000

---
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 100s
    ssl: false

redisson:
  keyPrefix:
  threads: 10
  nettyThreads: 10
  singleServerConfig:
    clientName: "prod"
    connectionMinimumIdleSize: 30
    connectionPoolSize: 50
    idleConnectionTimeout: 15000
    timeout: 25000
    subscriptionConnectionPoolSize: 5

---
mail:
  enabled: false

recovery:
  password: 123456

sms:
  is-print: false

checkOutValue: true

slave.port: 1504

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
